global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 4s

scrape_configs:
  - job_name: "simulation-backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["unacartaparaisabackend-backend-gpu-1:8080"]
        labels:
          service: "simulation"
          environment: "development"
    scrape_interval: 5s
    scrape_timeout: 4s

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          service: "prometheus"
    scrape_interval: 15s
