apiVersion: 1

datasources:
  - name: Simulation Prometheus
    uid: simulation-prometheus
    type: prometheus
    access: proxy
    url: http://uci-prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
      queryTimeout: "60s"
      httpMethod: "POST"
